D16_Bullboard/Bullboard/urls.py
from django.urls import path
from .views import *


urlpatterns = [
   path('confirm/', ConfirmUser.as_view(), name='confirm_user'),
   path('profile', ProfileView.as_view(), name='profile'),
   path('post/', PostList.as_view(), name='post_list'),
   path('post/<int:pk>/', PostDetail.as_view(), name='post_detail'),
   path('post/create/', PostCreate.as_view(), name='post_create'),
   path('post/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('comment/create/', CommentCreate.as_view(), name='comment_create'),
   path('comment/<int:pk>/', CommentDetail.as_view(), name='comment_detail'),
   path('comment/<int:pk>/edit/', CommentUpdate.as_view(), name='comment_update'),
   path('comment/<int:pk>/delete/', CommentDelete.as_view(), name='comment_delete'),
   path('signup/', SignUp.as_view(), name='signup'),
]

D16_Bullboard/D16_Bullboard/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/", include("accounts.urls")),
    path('board/', include('Bullboard.urls')),
    #path('ckeditor/', include('ckeditor_uploader.urls')),

]

D16_Bullboard/Bullboard/models.py
from django.urls import reverse_lazy
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    code = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.username


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)# Автор
    title = models.CharField(max_length=255)# Заголовок объявления
    text = models.TextField()# Текст объявления
    created = models.DateTimeField(auto_now_add=True)# Дата создания
    category = models.ForeignKey('Category', on_delete=models.CASCADE)# Категория
    upload = models.FileField(upload_to='uploads/%Y/%m/%d/', blank=True, default=None, null=True, verbose_name='upload')# Вложения

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('post_detail', kwargs={'pk':self.pk})



class Category(models.Model):
    name = models.CharField(max_length=64)
    subscribers = models.ManyToManyField(User, through='Subscriber')

    def __str__(self):
        return self.name


class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse_lazy('comment_detail', kwargs={'pk': self.pk})








D16_Bullboard/Bullboard/forms.py
from django.forms import ModelForm
from allauth.account.forms import SignupForm
from string import hexdigits
import random


from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django import forms
from .models import Post, Comment, User
from django.contrib.auth.forms import UserCreationForm


class PostForms(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class CommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        #fields = '__all__'
        fields = ['text']
        labels = {'author': 'Автор', 'post': 'Коментарий', 'text': 'Содержание коментария'}


class CommonSignupForms(SignupForm):
    def save(self, request):
        user = super(CommonSignupForms,self).save(request)
        user.is_active = False
        code = ''.join(random.sample(hexdigits, 5))
        user.code = code
        user.save()
        send_mail(
            subject= f'Код активации',
            message= f'Код активации аккаунта: {code}',
            from_email= settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
        )
        return user
class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )



D16_Bullboard/Bullboard/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import *
from .forms import PostForms, CommentForms
from .forms import SignUpForm

class PostList(ListView):

    model = Post # Указываем модель, объекты которой мы будем выводить
    ordering = '-created'     # Поле, которое будет использоваться для сортировки объектов
    template_name = 'post.html'  # Указываем имя шаблона,
    context_object_name = 'posts'  # имя списка, в котором будут лежать все объекты.чтобы обратиться к списку объектов в html-шаблоне
    #paginate_by = 10  # вот так мы можем указать количество записей на странице


class PostDetail(LoginRequiredMixin, DetailView):
    raise_exception = True
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['replay_form'] = CommentForms()
        return context

    #Добавление метода с формой отклика на страницу
    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = CommentForms(request.POST)
        if form.is_valid():
            replay = form.save(commit=False)
            replay.post = post
            replay.author = request.user
            replay.save()
            return redirect('post_detail', pk=post.pk)



class PostCreate(LoginRequiredMixin, CreateView):
    raise_exception = True
    form_class = PostForms
    model = Post
    template_name = 'post_create.html'
    context_object_name = 'create'


class PostUpdate(LoginRequiredMixin, UpdateView):
    form_class = PostForms
    model = Post
    template_name = 'post_edit.html'


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')



class CommentCreate(LoginRequiredMixin, CreateView):
    raise_exception = True
    form_class = CommentForms
    model = Comment
    ordering = '-created'
    template_name = 'comment_create.html'
    context_object_name = 'comment'


class CommentDetail(LoginRequiredMixin, DetailView):
    raise_exception = True
    model = Comment
    template_name = 'comment_detail.html'
    context_object_name = 'comments'


class CommentUpdate(LoginRequiredMixin, UpdateView):
    form_class = CommentForms
    model = Comment
    template_name = 'comment_edit.html'


class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'comment_delete.html'
    success_url = reverse_lazy('post_list')


class ConfirmUser(UpdateView):
    model = User
    context_object_name = 'confirm_user'

    def post(self, request, *args, **kwargs):
        if 'code' in request.POST:
            user = User.objects.filter(code=request.POST['code'])
            if user.exists():
                user.update(is_active=True)
                user.update(code=None)
            else:
                return  render(self.request,'users/invalid_code.html')
            return redirect('account_login')


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'


class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    success_url = '/accounts/login'
    template_name = 'registration/signup.html'

D16_Bullboard/templates/comment.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новый коментарий</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

D16_Bullboard/templates/comment_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новый коментарий</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

D16_Bullboard/templates/comment_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление комментария</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

D16_Bullboard/templates/comment_detail.html
{% extends 'flatpages/default.html' %}

{% block title %}
Comment
{% endblock title %}

{% block content %}
<h2>Комментарии: {{post.title}}</h2>
<h3>{{ comments.text }}</h3>
{% endblock content %}

D16_Bullboard/templates/comment_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Коментарий</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

D16_Bullboard/templates/post.html
{% extends 'flatpages/default.html' %}


{% block title %}
Posts
{% endblock title %}


{% block content %}
{% if posts %}
<table width="100%" style="margin-top: 35px">
    <tr>
        <td><u>Дата создания</u></td>
        <td><u>Автор</u></td>
        <td><u>Категория Объявления</u></td>
        <td><u>Заголовок объявления</u></td>
        <td><u>Объявление</u></td>
        <td><u>Вложения</u></td>

    </tr>

{% for post in posts %}

    <tr>
        <td>{{ post.created }}</td>
        <td>{{ post.author }}</td>
        <td>{{ post.category }}</td>
        <td>{{ post.title }}</td>
        <td>{{ post.text|safe }}</td>
        <td>{% if post.upload %}
            <p><img class="img-post-left" src="{{post.upload.url}}"></p>
                {% else %}
                Вложений нет
            {% endif %}
        </td>
    </tr>
{% endfor %}
</table>
{% else %}
<h3>"Пока объявлений  нет""</h3>
{% endif %}
{% endblock content %}


D16_Bullboard/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новая статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

D16_Bullboard/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление комментария</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

D16_Bullboard/templates/post_detail.html
{% extends 'flatpages/default.html' %}


{% block title %}
Comment
{% endblock title %}


{% block content %}
<h2>Объявление: {{post.title}}</h2>
<h3>{{ post.text }}</h3>

{% if user.is_authenticated %}
<h4>Добавить отклик</h4>
   
    <form method="post" style="...">
          {% csrf_token %}
            <div style="...">
                {{ replay_form.text }}
            </div>
            <button type="submit" class="btn btn-primary">Отправвить отклик</button>
    </form>
{% else %}
    <p>Авторизуйтесь, чтобы оставить отклик</p>
    <a  class="btn btn_primary", href="{% url 'profile' %}">Войти</a>
{% endif %}

{% if post.comment_set.all %}
<h4>Все отклики</h4>
    {% for reply in post.comment_set.all %}
        <div style="margin-top: 10px">

            <p> Автор: {{ reply.author}}   Текст отклика:{{ reply.text}}</p>
        </div>
    {% endfor %}
{% endif %}



<h3>{{ post.text }}</h3>


{% endblock content %}

D16_Bullboard/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Коментарий</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

D16_Bullboard/templates/users/invalid_code.html
{% extends 'flatpages/default.html' %}

{% block content %}
   <title>Активация аккаунта</title>
   <div class="text center mt-4 name" style="...">
       <h3> Активация аккаунта</h3>
   </div>
   <h4 style="..."> Неверный код активации </h4>
   <form style="...">
       <input type="button" onclick="history.back();" class="btn btn-outline-secondary btn-sm"
              value="Вернутся к вводу кода"/>
   </form>
{% endblock %}

D16_Bullboard/templates/users/profile.html
{% extends 'flatpages/default.html' %}

{% block content %}
<title>127.0.0.1:8000/users/profile/</title>
<div class="text center mt-4 name" style="...">
    <h3> Страница авторизованного пользователя</h3>
</div>
<p>
    <a href="{% url 'account_logout' %}">Выйти</a>
</p>
{% endblock %}